//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuyenDe08.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSPBan
    {
        public string MaChiTietSP { get; set; }
        public string MaSPTheoMau { get; set; }
        public string KichCo { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGiaBan { get; set; }
    
        public virtual SPTheoMau SPTheoMau { get; set; }
    }
}
