//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuyenDe08.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.SPTheoMaus = new HashSet<SPTheoMau>();
        }
    
        public string MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string MaPhanLoai { get; set; }

        [Column(TypeName = "numeric")]
        [RegularExpression("[1-9][0-9]*",ErrorMessage ="Must be a number")]
        [Range(100,10000)]
        public Nullable<decimal> GiaNhap { get; set; }
        [Column(TypeName = "numeric")]
        [RegularExpression("[1-9][0-9]*", ErrorMessage = "Must be a number")]
        [Range(100, 10000)]
        public Nullable<decimal> DonGiaBanNhoNhat { get; set; }
        [Column(TypeName = "numeric")]
        [RegularExpression("[1-9][0-9]*", ErrorMessage = "Must be a number")]
        [Range(100, 10000)]
        public Nullable<decimal> DonGiaBanLonNhat { get; set; }
        public string TrangThai { get; set; }
        public string MoTaNgan { get; set; }
        public string AnhDaiDien { get; set; }
        public string NoiBat { get; set; }
        public string MaPhanLoaiPhu { get; set; }
    
        public virtual PhanLoai PhanLoai { get; set; }
        public virtual PhanLoaiPhu PhanLoaiPhu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPTheoMau> SPTheoMaus { get; set; }
    }
}
